#!/bin/bash
# cave/archive - create a tar.xz of a given package's files
#
# Copyright 2016 Kylie McClain <kylie@somas.is>
# Distributed under the terms of the 0BSD license

set -euo pipefail

CAVE=${CAVE:-cave}

spec="$1"; shift
spec=$(${CAVE} print-ids -m "${spec}" -s uninstall --format '=%F\n')
cat=$(${CAVE} print-id-environment-variable "${spec}" --variable-name CATEGORY --format %v)
pn=$(${CAVE} print-id-environment-variable "${spec}" --variable-name PN --format %v)
pvr=$(${CAVE} print-id-environment-variable "${spec}" --variable-name PVR --format %v)
pnvr="${pn}-${pvr}"

files=(
    $(${CAVE} print-id-contents --format '%n\n' -t f "$spec" | cut -d'/' -f2-)
    $(${CAVE} print-id-contents --format '%n\n' -t s "$spec" | cut -d'/' -f2-)
    $(${CAVE} print-id-contents --format '%n\n' -t o "$spec" | cut -d'/' -f2-)
)

archive=${1:-${PWD}/${cat}---${pnvr}.tar}

[[ -f "${archive}" ]] && printf '%s already exists.\n' "${archive}" >&2 && exit 17

printf "creating an archive of %s/%s... " "${cat}" "${pnvr}" >&2

printf "%s\n" "${files[@]}" | tar -C / -T - --numeric-owner -cpf "${archive}"
xz -T 0 "${archive}" && printf '%s\n' "${archive}".xz
