#!/bin/sh
# cave/browse - open a package's HOMEPAGE in your $BROWSER
#
# Copyright 2015 Kylie McClain <kylie@somas.is>
# Distributed under the terms of the 0BSD license

BROWSER="${BROWSER:-xdg-open}"

for id in ${@};do
    for url in $(${CAVE:-cave} print-id-metadata -b "$id" --raw-name HOMEPAGE --format '%v\n');do
        ${BROWSER} "${url}"
    done
done
