#!/bin/sh

BROWSER="${BROWSER:-xdg-open}"

for id in ${@};do
    for url in $(${CAVE:-cave} print-id-metadata -b "$id" --raw-name HOMEPAGE --format '%v\n');do
        ${BROWSER} "${url}"
    done
done
