#!/bin/bash
# cave-update-pbins-matching-remote <ssh host(s)>
# update packages in a pbin repository if they are outdated
# on given ssh-connectible hosts
#
# Copyright 2015 Kylie McClain <somasis@exherbo.org>
# Distributed under the terms of the ISC License

SUDO=${SUDO:-sudo}
CAVE=${CAVE:-cave}

def_args=( "-z" "-1" )
upgrade_args=( "-Cs" )

set -e -o pipefail

cave() {
    eval "command ${SUDO} ${CAVE} $@ || die $?"
}

die() {
    echo "${0##*/}: dying with error code $1"
    exit $1
}

help() {
    echo "usage: ${0##*/} [-cave resolve arguments] <ssh host(s)>"
}

if [[ "$#" -lt 1 ]];then
    help
    exit 2
fi

args=()
hosts=()

while [[ "$#" -ne 0 ]];do
    if [[ "$1" == "-x" ]];then
        args+=( $1 )
        upgrade_host=true
    elif [[ "$1" == "-"* ]];then
        args+=( $1 )
    else
        hosts+=( $1 )
    fi
    shift
done

echo "synchronizing repositories on local..."
cave sync

for host in ${hosts[@]};do
    echo "${host}: synchronizing repositories on remote..."
    ssh -t "$host" "$SUDO" "$CAVE" sync || die $?
    echo "${host}: getting outdated packages..."
    remote_packages=(
        $(echo $(ssh "${host}" "$SUDO" "$CAVE" report | grep 'Has better version' | cut -d':' -f2-))
    )

    remote_packages_new=(
        $(for pkg in ${remote_packages[@]};do
            eval "$(cave print-id-environment-variable =${pkg} --variable-name CATEGORY --variable-name PN --variable-name SLOT)"
            echo "${CATEGORY}/${PN}:${SLOT}"
        done)
    )

    remote_packages=( ${remote_packages_new[@]} )
    remote_packages_new=

    echo "${host}: \`\"$SUDO\" \"$CAVE\" resolve -1 --make binaries ${def_args[@]} ${args[@]} ${remote_packages[@]}\`..."
    for pkg in ${remote_packages[@]};do
        printf '%s\0' "${pkg}"
    done | xargs -0 "$SUDO" "$CAVE" resolve -Ks --make binaries "${def_args[@]}" "${args[@]}" || die $?

    if [[ "$upgrade_host" ]];then
        echo "${host}: synchronizing repositories on remote..."
        ssh -t "${host}" "$SUDO" "$CAVE" sync || die $?
        echo "${host}: upgrading world on remote host..."
        echo "${host}: \`\"$SUDO\" \"$CAVE\" resolve -cx world\`"
        ssh -t "${host}" "$SUDO" "$CAVE" resolve "${upgrade_args[@]}" -cx world || die $?
    fi
done
