#!/bin/bash
# cave-update-pbins-matching-remote <ssh host(s)>
# update packages in a pbin repository if they are outdated
# on given ssh-connectible hosts
#
# Copyright 2015, Kylie McClain <somasissounds@gmail.com>
# Distributed under the terms of the ISC License

SUDO=${SUDO:-sudo}
CAVE=${CAVE:-cave}

def_args=( "-z" "-1" )

set -e -o pipefail

help() {
    echo "usage: ${0##*/} [-cave resolve arguments] <ssh host(s)>"
}

if [[ "$#" -lt 1 ]];then
    help
    exit 2
fi

args=()
hosts=()

while [[ "$#" -ne 0 ]];do
    if [[ "$1" == "-"* ]];then
        args+=( $1 )
    else
        hosts+=( $1 )
    fi
    shift
done

for host in ${hosts[@]};do
    echo "${host}: synchronizing repositories..."
    ssh -t "$host" -- "$SUDO" -- "$CAVE" sync
    echo "${host}: getting outdated packages..."
    remote_packages=(
        $(echo $(ssh "${host}" -- "$SUDO" "$CAVE" report | grep 'Has better version' | cut -d':' -f2-))
    )

    remote_packages_new=(
        $(for pkg in ${remote_packages[@]};do
            eval "$(cave print-id-environment-variable =${pkg} --variable-name CATEGORY --variable-name PN --variable-name SLOT)"
            echo "${CATEGORY}/${PN}:${SLOT}"
        done)
    )

    remote_packages=( ${remote_packages_new[@]} )
    remote_packages_new=

    echo "${host}: packages needing updating:"
    for pkg in ${remote_packages[@]};do
        printf "${host}"': \t%s\n' "${pkg}"
    done
    echo "${host}: \`\"$SUDO\" \"$CAVE\" resolve -1 --make binaries ${def_args[@]} ${args[@]}\`..."
    for pkg in ${remote_packages[@]};do
        printf '%s\0' "${pkg}"
    done | xargs -0 "$SUDO" "$CAVE" resolve -Ks -Si -si --make binaries "${def_args[@]}" "${args[@]}"
done
