#!/bin/bash
# comptond - run compton as a daemon and refresh on config changes

comptond_conf="$HOME/.config/comptond.conf"
watch="$comptond_conf"

while true;do
    ATIME=$(stat -c %Z "$watch")
    if [[ ! -z $(pgrep 'xfwm4') && "$ATIME" != "$LTIME" || -z $(pgrep '^compton$') ]]; then
        pkill ^compton$
        . "$comptond_conf"
        eval compton $compton_args &
        LTIME=$ATIME
    else
        sleep 2s
    fi
#    compton $compton_args
done
