#!/bin/sh

PS4="${0##*/}[$$]: "

. "${XDG_CONFIG_HOME:-~/.config}"/"${0##*/}"/config

if [ "$#" -ne 0 ];then
    exec restic "$@"
fi

if [ "$(id -u)" -eq 0 ];then
    set -x
    touch /var/log/"${0##*/}".log
    chmod -R 770 /var/log/"${0##*/}".log
    chown -R restic:restic /var/log/"${0##*/}".log
    exit $?
fi

restic backup \
    -v \
    --exclude-caches \
    --exclude-file "${XDG_CONFIG_HOME:-~/.config}"/"${0##*/}"/excludes \
    --one-file-system \
    /etc /home /var \
    2>&1 | s6-tai64n | tee -a /var/log/"${0##*/}".log

