#!/bin/bash

if [[ "$1" == '--' ]];then
    shift
fi

arg=$(echo "$@" | sed 's/^-e //')
if [[ -z "$arg" ]] && grep -q exo-helper /proc/$PPID/comm && [[ "$(pgrep -l ^germinal 2>&1 | grep -v germinal-one)" ]];then
    tmux new-window "cd '${PWD}' && exec $SHELL"
    wmctrl -i -a $(wmctrl -l | grep germinal | cut -d' ' -f1)
elif [[ -z "${arg}" && "$(pgrep -l ^germinal 2>&1 | grep -v germinal-one)" ]]; then
    echo "switching to running instance" >&2
    wmctrl -i -a $(wmctrl -l | grep germinal | cut -d' ' -f1)
elif [[ -n "${arg}" && "$(pgrep -l ^germinal 2>&1 | grep -v germinal-one)" ]];then
    tmux new-window "$arg"
    wmctrl -i -a $(wmctrl -l | grep germinal | cut -d' ' -f1)
elif [[ -z "${arg}" ]];then
    exec germinal
elif [[ -n "${arg}" ]];then
    exec germinal -- tmux new -As0 "${arg}"
else
    echo "whoops lol"
    exit 2
fi
