#!/bin/bash
# git-resurrect - bring back the last version of a file/directory that existed
#
# Copyright 2015 Kylie McClain <kylie@somas.is>
# Distributed under the terms of the 0BSD license

for FILE in "$@";do
    git checkout $(git rev-list -2 HEAD -- "${FILE}" | tail -1) -- "${FILE}"
done

