#!/bin/bash

branch=$(git rev-parse --abbrev-ref HEAD)
remote=$(git config "branch.${branch}.remote")
since=$(git log --oneline "${remote}/${branch}".."${branch}" | wc -l)

git log --reverse "$@" HEAD~${since}..HEAD
