#!/bin/bash

branch=$(git rev-parse --abbrev-ref HEAD)
remote=$(git config "branch.${branch}.remote")

if [[ $# -lt 1 ]];then
    timeframe=HEAD~$(git log --oneline "${remote}/${branch}".."${branch}" | wc -l)..HEAD
else
    timeframe="${1}"
    shift
fi


git log --reverse "${timeframe}" "${@}"
