#!/bin/sh
# gmail-open - opens gmail and parses mailto link if given one
# useful for setting as default mail client in desktop environments
#
# Copyright 2015-2017 Kylie McClain <kylie@somas.is>
# Distributed under the terms of the 0BSD license

if [[ "$@" ]];then
    xdg-open "https://mail.google.com/mail?view=cm&tf=0&to=$(echo $@ | sed 's/mailto://;s/?/\&/;s/&subject=/\&su=/')"
else
    xdg-open "https://mail.google.com/"
fi
