#!/bin/sh

if [ "$#" -eq 0 ];then
    printf 'usage: %s [OPTIONS] PATTERN FILE...\n' "${0##*/}" >&2
    exit 1
fi

while [ "$#" -ne 0 ];do
    case "$1" in
        --)
            shift
            break
        ;;
        -*)
            grep_args+=( "${1}" )
            shift
        ;;
        *)
            break
        ;;
    esac
done

PATTERN="${1}"; shift

if [ "$#" -lt 2 ];then
    gpgcat "${1}" | grep "${grep_args[@]}" -- "${PATTERN}"
else
    for f in "$@";do
        export f # pipes may be ran in subshells
        gpgcat "${f}" | grep "${grep_args[@]}" -n -- "${PATTERN}" | while read -r line;do
            printf '%s:%s\n' "${f}" "${line}"
        done
    done
fi
