#!/bin/ksh
# mdnsd-resolve-hack -- resolve hosts discovered by openmdnsd in any program
# note: if you run Bitrig, this is not useful. it is implemented in the system
# resolver now. check the manpage resolv.conf(5).
# written by Somasis <somasis@cryptolab.net> - 2014
#
hosts_file=/etc/hosts
tmp_file=/tmp/mdnsd-resolve-hack-$$

error_out() {
    errcode=${errcode:-$?}
    echo "# ${1:-error, closing down.} (errcode: $errcode)"
    exit $errcode
}

remove_old_entries() {
    sed 's/.*# inserted by mdnsd-resolve-hack//' "$hosts_file" | grep -v '^$' | sort -u >> "${tmp_file}-2"
    editing_errcode="$?"
    if [[ "$editing_errcode" -ne 0 ]];then
        error_out
    else
        echo "# successfully wiped out old entries!"
    fi
}

trap 'for job in $(jobs -p);do kill "$job" >/dev/null 2>&1; kill "$job" >/dev/null 2>&1;done; remove_old_entries; exit' 2 3 15

if [ "$(id -un)" -ne 0 ];then
    echo "# you must run this script as root"
    exit 2
fi

echo "# hosts_file: $hosts_file"
echo "# tmp_file: $tmp_file"
echo "# backing up $hosts_file to $hosts_file.bak"
cp "$hosts_file" "${hosts_file}.bak" || error_out "failed to make backup"

while true;do
    { { mdnsctl browse -r > "$tmp_file" 2>/dev/null; } & sleep 2; kill %+; }
    found_hosts=$(grep -e Target -e Address "$tmp_file" | tr '\n' ':' | sed 's/ Target: /;/g;s/: Address: /:/g;s/:;/;/g;s/:$//' | tr ';' '\n' | sort -u)
    :>"$tmp_file"
    for host in $found_hosts;do
        hostname=$(echo "$host" | cut -d':' -f1)
        ip=$(echo "$host" | cut -d':' -f2)
        echo "$ip $hostname # inserted by mdnsd-resolve-hack"
        echo "$ip $hostname # inserted by mdnsd-resolve-hack" >> "$tmp_file"
    done

    remove_old_entries
    echo
    echo "# generated file, now overwriting $hosts_file with it"
    cat "${tmp_file}-2" "$tmp_file" > "$hosts_file"
    rm "$tmp_file" "${tmp_file}-2"
    echo "# sleeping for 30 seconds"
    sleep 30
done
