#!/bin/sh

rating="${1:-0}"
mpc_rating=$(expr "${rating}" + "${rating}")
mpc sticker "$(mpc current -f '%file%')" set rating "${mpc_rating}"
song=$(mpc current -f "[%artist% - ]%title%[ (%album%)]")

if [ "${rating}" -gt 0 ];then
    stars=
    for i in $(seq 1 "${rating}");do
        stars="${stars}★"
    done
fi

if [ "${#stars}" -ne 5 ];then
    while [ $(printf '%s' "${stars}" | wc -m) -le 6 ];do
        stars="${stars}☆"
    done
    stars="${stars:0:5}"
fi

notification mpc-star -u low -i multimedia-audio-player "mpc-star" "${song} ${stars}"
