#!/usr/bin/env bash
# mpd-on-same-album - set replaygain and crossfade based on what track is next - version 0.1
#
# Copyright 2014-2015 Kylie McClain <somasis@exherbo.org>
# Distributed under the terms of the ISC License
# https://github.com/somasis/scripts/

set_replaygain=true # if you want replaygain to be set
preferred_crossfade=2 # what to set crossfade to if next song is not from same album

## Script begins here

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
config_location="${XDG_CONFIG_HOME}/mpd-on-same-album.conf"

while true; do
    [[ -f "$config_location" ]] && . "$config_location"
    [[ "${preferred_crossfade:-$old_preferred_crossfade}" == "${old_preferred_crossfade}" ]] || echo "Crossfade length: $preferred_crossfade" >&2; old_preferred_crossfade="${preferred_crossfade}"
    [[ "${set_replaygain:-$old_set_replaygain}" == "${old_set_replaygain}" ]] || echo "Set replaygain: $set_replaygain" >&2; old_set_replaygain="${set_replaygain}"

    if [[ $(mpc playlist | wc -l) != 0 ]];then # playlist is not empty
        old_np="$np"
        old_next="$next"
        np=$(mpc -f '%position% [%albumartist%|%artist%] - %album% (%date%)' current --wait)
        np_num=${np/ *}
        np=${np#* }
        crossfade=$(mpc crossfade | cut -d' ' -f2)
        next=$(mpc -f "[%albumartist%|%artist%] - %album% (%date%)" playlist | tail -n $(( $(mpc playlist 2>/dev/null | wc -l) - $np_num )) | head -n 1)
        replaygain=$(mpc replaygain | cut -d' ' -f2)
        if [[ "$old_np" != "$np" ]];then
            echo "Now playing: $np" >&2
        fi
        if [[ "$old_next" != "$next" ]];then
            echo "Next song: $next" >&2
        fi
        if mpc status | tail -n 1 | grep -q 'random: off' && [[ "$np" == "$next" ]];then
            if [[ "$crossfade" != 0 ]];then
                mpc crossfade 0
                echo "Crossfade set to: 0" >&2
            fi
            if [[ "$set_replaygain" == true && "$replaygain" != "$old_replaygain" ]];then
                mpc replaygain "album"
                echo "Replaygain set to: album mode" >&2
            fi
        else
            if [[ "$crossfade" != "$preferred_crossfade" ]];then
                mpc crossfade "$preferred_crossfade"
                echo "Crossfade set to: $preferred_crossfade" >&2
            fi
            if [[ "$set_replaygain" == true && "$replaygain" != "$old_replaygain" ]];then
                mpc replaygain track
                echo "Replaygain set to: track mode" >&2
            fi
        fi
    else
        sleep 2
    fi
done
