#!/bin/bash
# OldNotifier.sh -- notifier for The Old Reader
# (c) 2014 Somasis <somasissounds@gmail.com>

## Don't change these variables, use $XDG_CONFIG_HOME/oldnotifier.conf for your own settings!
email=
password=
notify_for="total"
notify_every="1h"
wait_until_top_of_house="false"

if [[ -z "$XDG_CONFIG_HOME" ]];then
    XDG_CONFIG_HOME="$HOME/.config"
fi

. "$XDG_CONFIG_HOME/oldnotifier.conf"

if [[ "$email" != *@* ]];then
    echo "You must supply an email, not a username"
    exit 1
fi

if [[ "$wait_until_top_of_hour" == "true" ]];then
    current_epoch=$(date +"%s")
    target_epoch=$(date -d "$(( $(date +%H) + 1 )):00:00" +%s)
    sleep_seconds=$(( $target_epoch - $current_epoch ))
    echo "Waiting until $(date +$(( $(date +%H) + 1 )):00)..."
    sleep "$sleep_seconds"
fi

key=$(curl -sd "client=OldNotifier.sh&accountType=HOSTED&service=reader&Email=$email&Passwd=$password" "https://theoldreader.com/accounts/ClientLogin" | grep "^Auth=" | cut -d'=' -f2)

if [[ -z "$key" ]];then
    echo "Key is invalid, check your password or email configuration"
    exit 2
fi

while true; do
    unread_raw=$(curl -sH "Authorization: GoogleLogin auth=$key" "https://theoldreader.com/reader/api/0/unread-count?output=json" | sed 's/[0-9],/&,\n/g' | sed 's/","count":/:/g;s/.*id":"//g;s/,,//g;s/.*}]}//;s/{"//g;s/":/:/g' | grep -v '^$')
    if [[ -z "$unread_raw" ]];then
        echo "Failed to get unread count, run this script with bash -x to get debug output"
        exit 3
    fi

    unread_total=$(echo "$unread_raw" | grep "^max:" | cut -d':' -f20)
    unread_feeds=$(echo "$unread_raw" | grep '^feed/' | cut -d'/' -f2)
    unread_labels=$(echo "$unread_raw" | grep 'label/' | cut -d'/' -f4)

    if [[ "$notify_for" == "total" ]];then
        notify-send "The Old Reader" "You have $unread_total unread articles"
    fi
    
    sleep "$notify_every"
done