#!/bin/sh
# pacman-mirrorlist-update - rank a list of mirrors
#
# Copyright 2018 Kylie McClain <kylie@somas.is>
# Distributed under the terms of the 0BSD license

if ! [ -w /etc/pacman.d/mirrorlist ];then
    printf "%s: can't write to /etc/pacman.d/mirrorlist\n" "${0##*/}" >&2
    exit 127
fi

tmp1=$(mktemp)
tmp2=$(mktemp)

for f in /etc/pacman.d/mirrorlist{,.pacnew};do
    [ -f "${f}" ] && cat "${f}"
done >> "${tmp1}"

sed -E '/^# Server = / s/# //;/^#/d' -i "${tmp1}"
rankmirrors -n 0 -v "${tmp1}" >> "${tmp2}"
mv -f "${tmp2}" /etc/pacman.d/mirrorlist
rm -f "${tmp1}" /etc/pacman.d/mirrorlist.pacnew
