#!/bin/sh
# playerctl-cdprev - add CD-like previous command; goes to beginning of track,
#                    and then next track if done in three seconds of doing that

if [ -f ~/.playerctl-cdprev ] || [ $(playerctl "${@}" position) -lt 4 ];then
    playerctl "${@}" previous
else
    touch ~/.playerctl-cdprev
    playerctl "${@}" position 0
    sleep 3
    rm -f ~/.playerctl-cdprev
fi

