#!/bin/sh

if [ -f ~/.playerctl-cdprev ] || [ $(playerctl "${@}" position) -lt 4 ];then
    playerctl "${@}" previous
else
    touch ~/.playerctl-cdprev
    playerctl "${@}" position 0
    sleep 3
    rm -f ~/.playerctl-cdprev
fi

