#!/bin/bash
# sort_mirrors - rank the list of openbsd mirrors
# (c) 2014 Somasis <somasissounds@gmail.com> - MIT License
# https://github.com/Somasis/scripts/

non_rsync_gettime() {
    begin_time=$(date +"%s.%N")
    wget -T 5 -t 1 -O /dev/null "$mirror" 2>&1 >/dev/null || begin_time=$(( $(date +%s) * 1000 ))
    end_time=$(date +"%s.%N")
    total=$(echo "scale=2;$end_time-$begin_time" | bc)
    echo "$total $mirror"
}

rsync_gettime() {
    begin_time=$(date +"%s.%N")
    rsync --timeout=5 "$mirror" 2>&1 >/dev/null || begin_time=$(( $(date +%s) * 1000 ))
    end_time=$(date +"%s.%N")
    total=$(echo "scale=2;$end_time-$begin_time" | bc)
    echo "$total $mirror"
}

get_mirror_list() {
    wget -T 5 -t 1 -qO - "http://www.openbsd.org/build/mirrors.dat" | sed '/:\/\//!d;s/^#..//;s/^[[:alpha:]][[:alpha:]]//;s/^[ \t]*//'
}

measure_mirrors() {
    for mirror in $(get_mirror_list);do
        case "$mirror" in
            http*|ftp*)
            non_rsync_gettime "$mirror"
            ;;
            rsync*)
            rsync_gettime "$mirror"
            ;;
            *)
            non_rsync_gettime "$mirror" || rsync_gettime "$mirror"
            ;;
        esac
    done
}

mirrors_sorted=$(measure_mirrors | sort -n)
echo "$mirrors_sorted" | tr '\n' ':'
