#!/bin/sh
# tmux-shell - command to give status-bar information

if [ -z "${DISPLAY}" ];then
    np=$(mpc -f '[%artist% - ]%title%[ (%album%)]' current | cut -c-73)
    clock_local=$(date '+%I:%M:%S%p')
    clock_violet=$(TZ=Australia/Adelaide date '+%I:%M:%S%p')
fi

for item in "${np}" "${battery}" "${clock_violet}" "${clock_local}";do
    [ -z "${item}" ] && continue
    if [ -z "${output}" ];then
        output="${item}"
    else
        output="${output} - ${item}"
    fi
done

printf '%s' "${output}"

