#!/bin/bash
# toggle-touchpad - toggle the first detected touchpad with xfconf/xinput
#
# Copyright 2014-2015 Kylie McClain <kylie@somas.is>
# Distributed under the terms of the 0BSD License

if type -fPp xfconf-query >/dev/null 2>&1 && [ "${DESKTOP_SESSION}" = XFCE ];then
    method=${method:-xfconf}
    touchpad=$(xfconf-query -c pointers -l | grep /Properties/Device_Enabled | grep '[Tt]ouchpad' | cut -d'/' -f2 | head -1)
    name="${touchpad//_/ }"
    state=$(xfconf-query -c pointers -p "/$touchpad/Properties/Device_Enabled")
elif type -fPp xinput >/dev/null 2>&1;then
    method=${method:-xinput}
    touchpad=$(xinput list | egrep -io 'touchpad\s*id\=[0-9]{1,2}' | egrep -o '[0-9]{1,2}')
    name=$(xinput list --name-only "$touchpad")
    state=$(echo $(xinput list-props "$touchpad" | grep 'Device Enabled') | cut -d' ' -f4)
else
    notify-send -a toggle-touchpad
    printf '%s: %s\n' "${0##*/}" "can't figure out method to turn off touchpad"
    exit 127
fi

enable_touchpad() {
    case "$method" in
        xinput)
            xinput enable "$touchpad"
        ;;
        xfconf)
            xfconf-query -c pointers -p "/$touchpad/Properties/Device_Enabled" -s 1
        ;;
    esac
}

disable_touchpad() {
    case "$method" in
        xinput)
            xinput disable "$touchpad"
        ;;
        xfconf)
            xfconf-query -c pointers -p "/$touchpad/Properties/Device_Enabled" -s 0
        ;;
    esac
}

# state should be a boolean, with 0 being off and 1 being on
if [[ "$state" -eq 1 ]];then
    echo "Turning off ${name:-$touchpad}..."
    disable_touchpad
else
    echo "Turning on ${name:-$touchpad}..."
    enable_touchpad
fi
