#!/usr/bin/env bash
# xfce4-screenshooter-handler -- wrap xfce4-screenshooter
# (c) 2014 Kylie McClain <somasissounds@gmail.com> - MIT License
# https://github.com/somasis/scripts/

urlencode() {
    local string="${1}"
    local strlen=${#string}
    local encoded=""

    for (( pos=0 ; pos<strlen ; pos++ )); do
        c=${string:$pos:1}
        case "$c" in
            [-_.~a-zA-Z0-9] ) o="${c}" ;;
            * )               printf -v o '%%%02x' "'$c"
        esac
        encoded+="${o}"
    done
    echo "${encoded}"
    ENCODED="${encoded}"
}

wrap_mode_action() {
    filename=$(basename "$file")
    url_encoded_filename=$(urlencode "$filename")
    copy_to="$HOME/Sync/Public"
    final_url="https://etc.somasis.com/sync/$url_encoded_filename"
    echo "\"$filename\" -> \"$copy_to/$filename\"..."
    cp "$file" "$HOME/Pictures/Screenshots"
    mv "$file" "$copy_to/$filename"
    echo "$final_url" | xclip -in -selection clipboard
    notify-send -i "applets-screenshooter" "Screenshot" "Screenshot url copied to clipboard."
    exit
}

while [[ $# -ne 0 ]];do
    if [[ "$1" == -* ]];then
        arg="$1"
        shift
    else
        file="$1"
        shift
    fi
    case $arg in

        --wrap)
        wrap_mode=true
        ;;
        *)
        args=" $arg$args"
        ;;
    esac
done

if [[ "$wrap_mode" != "true" ]];then
    xfce4-screenshooter $args -o "$0 --wrap"
else
    wrap_mode_action
fi
