# Set default interface options
set-option global ui_options \
    ncurses_assistant=cat \
    ncurses_set_title=true \
    ncurses_status_on_top=true

# Disable startup changelog unless development version.
set-option global startup_info_version -1

# Set default text-editing options
set-option global tabstop 4
set-option global indentwidth 4

# Set options for default plugins
set-option global autowrap_column 100
set-option global makecmd 'make -j12'

# Keybinds
## Kakoune // Change to previous buffer // alt + a
map global normal <a-a> ':buffer-previous<ret>'
## Kakoune // Change to next buffer // alt + shift + a
map global normal <a-A> ':buffer-next<ret>'

# Plugins

## kak-lsp, not managed by plug.kak.
eval %sh{ kak-lsp --kakoune -s $kak_session }
hook global WinSetOption filetype=(c|cpp) %{
    lsp-enable-window
}

## Bootstrap plug.kak if it's not installed.
evaluate-commands %sh{
    plugin_dir="${XDG_DATA_HOME}/kak/plugins"
    mkdir -p "${plugin_dir}"
    [ -e "$plugin_dir/plug.kak" ] \
        || git clone -q https://github.com/andreyorst/plug.kak "${plugin_dir}/plug.kak"
    printf "%s\n" "source '${plugin_dir}/plug.kak/rc/plug.kak'"
}

plug "https://github.com/matthias-margush/tug"          # File management commands.
plug "https://github.com/alexherbo2/auto-pairs.kak"     # Auto-add matching parenthesis.
plug "https://github.com/whereswaldon/shellcheck.kak"   # Automatically lint shell scripts.
plug "https://github.com/occivink/kakoune-find"         # Find and replace across buffers.
plug "https://gitlab.com/Screwtapello/kakoune-inc-dec"  # Increment/decrement numbers with <c-[ax]>
plug "https://github.com/caksoylar/kakoune-smooth-scroll" config %{
    hook global -group user-smooth-scroll WinCreate .* %{
        hook -once window -group user-smooth-scroll WinDisplay .* smooth-scroll-enable
    }
}

## Filetypes
plug "https://github.com/gspia/csv.kak"                 # Highlight columns of CSV files.
plug "https://github.com/Ordoviz/mediawiki.kak"         # Syntax highlighting for MediaWiki markup.

# Highlight hexadecimal colors in buffers.
#plug "https://github.com/alexherbo2/palette.kak" config %{
#    # Update palette on each key.
#    hook global InsertIdle .* %{
#        palette-update
#    }
#}

# Change cursor color on inactive window.
plug "https://github.com/greenfork/active-window.kak" config %{
    set-face global InactiveCursor default,rgb:5d5d5d
}

# Integrate yank with Xorg clipboard.
plug "https://github.com/lePerdu/kakboard" config %{
    hook global -group user-kakboard WinCreate .* %{ kakboard-enable }
}

# Easier indentation style management.
plug "https://github.com/andreyorst/smarttab.kak" defer smarttab %{
    set-option global softtabstop 4
} config %{
    # Default to using spaces for everything.
    hook global -group user-smarttab BufOpenFile .* %{ expandtab }
    hook global -group user-smarttab BufNewFile  .* %{ expandtab }

    # With exceptions.
    hook global -group user-smarttab BufOpenFile .*\.scd noexpandtab
    hook global -group user-smarttab WinSetOption filetype=(makefile) smarttab
    hook global -group user-smarttab WinSetOption filetype=(c|cpp) smarttab
    hook global -group user-smarttab BufOpenFile .*/git/config %{ smarttab }
    hook global -group user-smarttab BufOpenFile .*\.git/config %{ smarttab }
}

# Hooks
hook -group user-wincreate global WinCreate ^[^*]+$ %{
    autowrap-enable
}

hook -group user-bufcreate global BufCreate .* %{
    modeline-parse
    git show-diff
}

hook -group user-bufwritepre global BufWritePre .* %{
    ## Make directory for buffer prior to writing it.
    nop %sh{ mkdir -p "$(dirname "$kak_hook_param")" }
}

hook -group user-bufwritepost global BufWritePost .* %{
    git show-diff
}

## Lightly enforce the 50/72 rule for git commit summaries.
hook global -group user-git-commit WinSetOption filetype=git-commit %{
    set-option buffer autowrap_column 72

    # <https://github.com/kakoune-editor/kakoune-extra-filetypes/blob/master/rc/git-commit-overflow.kak>
    # Commit title; everything over 50 is yellow.
    add-highlighter window/ regex \A\n*[^#\n]{50}([^\n]+) 1:black,yellow+f

    # Line following the title should be empty
    add-highlighter window/ regex \A[^\n]*\n([^#\n]+) 1:white,red+b
}

## scdoc(1).
hook global -group user-scd BufCreate .*\.scd %{
    set-option buffer filetype markdown
    set-option buffer autowrap_column 80
}

## man(7) and mdoc(7).
hook global -group user-troff WinSetOption filetype=troff %{
    set-option buffer autowrap_column 72

    # Update all .Dd dates before saving the buffer.
    hook buffer -group user-troff-update-date BufWritePre .* %{
        execute-keys -draft \
            <esc>% \
            s^\.Dd<ret> \
            x \
            |date<space>+".Dd<space>%B<space>%d,<space>%Y"<ret><esc>
    }
}

## pass(1) temporary files.
hook global -group user-password-store BufCreate /dev/shm/pass\..* %{
    set-option buffer filetype yaml
    autowrap-disable
}

## Used by aerc(1).
hook global -group user-aerc WinSetOption filetype=mail %{
    set-option buffer autowrap_column 72
    set-option buffer autoreload no
}

## Use tab/shift-tab for completion.
hook global -group user-completion InsertCompletionShow .* %{
    map window insert <tab> <c-n>; map window insert <s-tab> <c-p>
}

hook global -group user-completion InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>; unmap window insert <s-tab> <c-p>
}

# Update autowrap column highlighter when it changes.
hook global -group user-autowrap-highlight BufSetOption autowrap_column=.* %{
    add-highlighter -override global/wrap column %opt{autowrap_column} default,black
}

# Highlighters

## Number lines, show whitespaces.
add-highlighter global/ number-lines -separator " ▏" -hlcursor -min-digits 3
add-highlighter global/ show-whitespaces -spc " " -tab "→"
add-highlighter global/ show-matching

## Highlight issues, nasty code, and notes, in descending order of goodness.
add-highlighter global/ regex \W(BUG|FIXME)(\((\S+)\))? 1:white,red+bf      2:white,blue+f
add-highlighter global/ regex \W(HACK|XXX)(\((\S+)\))?  1:black,yellow+bf   2:white,blue+f
add-highlighter global/ regex \W(NOTE|TODO)(\((\S+)\))? 1:black,green+bf    2:white,blue+f

## Highlight trailing spaces.
add-highlighter global/ regex \h+$ 0:default,red+f

## Highlight the autowrapping column, highlight any characters past that column.
add-highlighter global/ wrap -word
add-highlighter global/ regex "^[^\n]{%opt{autowrap_column}}([^\n]+)$" 1:white,red+bf

## Highlight word under the cursor.
declare-option -hidden regex curword
set-face global CurWord PrimarySelection

hook global -group user-highlight-cursor-word NormalIdle .* %{
    eval -draft %{
        try %{
            exec <space><a-i>w <a-k>\A\S+\z<ret>
            set-option buffer curword "\b\Q%val{selection}\E\b"
        } catch %{
            set-option buffer curword ''
        }
    }
}

add-highlighter global/ dynregex '%opt{curword}' 0:CurWord
