#!/bin/sh

# Fix the fallback `X` cursor on root window
xsetroot -cursor_name left_ptr

bspc monitor -d 1 2 3 4 5

# Layout specific settings
bspc config borderless_monocle true     # Remove borders of windows in the monocle layout
bspc config gapless_monocle true        # Remove gaps between windows in the monocle layout
bspc config single_monocle true         # Set the layout for the desktop to monocle if there's only one window
bspc config center_pseudo_tiled true    # Center pseudo tiled windowed in their rectangles

bspc config focus_follows_pointer true  # Focus the window under the pointer
bspc config split_ratio 0.50            # Split newly created windows 50% by default.

# Window appearance
bspc config normal_border_color     '#17181a'
bspc config active_border_color     '#ef9324'
bspc config focused_border_color    '#ef9324'
bspc config border_width 8
bspc config window_gap 24

bspc config automatic_scheme alternate

bspc config pointer_modifier mod4           # Super key
bspc config pointer_action1 move            # Move windows during left click+hold
bspc config pointer_action3 resize_corner   # Resize windows from corner during right click+hold

# Window rules
bspc rule -r '*'
