#!/bin/sh

# Fix the fallback `X` cursor on root window
xsetroot -cursor_name left_ptr

for monitor in $(xrandr -q | grep " connected" | cut -d ' ' -f1); do
    bspc monitor "${monitor}" -d 1 2 3 4 5
done

# Multihead settings
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

# Layout specific settings
bspc config borderless_monocle true     # Remove borders of windows in the monocle layout
bspc config gapless_monocle true        # Remove gaps between windows in the monocle layout
bspc config single_monocle true         # Set the layout for the desktop to monocle if there's only one window
bspc config center_pseudo_tiled true    # Center pseudo tiled windowed in their rectangles

bspc config focus_follows_pointer true  # Focus the window under the pointer
bspc config split_ratio 0.50            # Split newly created windows 50% by default.

# Window appearance
bspc config normal_border_color     '#2f343f'
bspc config active_border_color     '#ac5f6c'   # Active on a monitor, not necessarily the focused.
bspc config focused_border_color    '#5294e2'   # Active on the focused monitor.
bspc config border_width 4
bspc config window_gap 16

bspc config top_padding 32

bspc config automatic_scheme alternate

bspc config pointer_modifier mod4           # Super key
bspc config pointer_action1 move            # Move windows during left click+hold
bspc config pointer_action3 resize_corner   # Resize windows from corner during right click+hold

# Window rules
bspc rule -r '*'

# Workarounds for programs drawing their own decorations.
bspc rule -a Steam border=off

# Main FL Studio workspace.
bspc rule -a fl.exe border=off
bspc rule -a fl.exe state=tiling

# Dialogs produced by FL itself.
bspc rule -a "fl.exe:*:FL Studio 20" border=off

# Xmascot.
for r in state=floating layer=below sticky=on manage=off; do
    bspc rule -a "*:XMascot" "${r}"
done
