#!/bin/sh

eval $(dbus-launch --sh-syntax)

# Initialize systemd crap.
. /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

export DESKTOP_SESSION=bspwm

# Read in Xresources.
xrdb -merge "${XDG_CONFIG_HOME:-~/.config}"/X11/xresources

# Set wallpaper.
xwallpaper --zoom "${XDG_CONFIG_HOME:-~/.config}"/X11/wallpaper-zoom

# Disable touchscreen.
xinput-toggle -d "Wacom HID 50FD Finger touch"

exec catsitd-xorg -d
